# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uart_platform/uart_platform.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform || ORIG_REF_NAME==uart_platform} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_microblaze_0_0/uart_platform_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_microblaze_0_0 || ORIG_REF_NAME==uart_platform_microblaze_0_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_dlmb_v10_0/uart_platform_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_dlmb_v10_0 || ORIG_REF_NAME==uart_platform_dlmb_v10_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_ilmb_v10_0/uart_platform_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_ilmb_v10_0 || ORIG_REF_NAME==uart_platform_ilmb_v10_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_dlmb_bram_if_cntlr_0/uart_platform_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uart_platform_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_ilmb_bram_if_cntlr_0/uart_platform_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uart_platform_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_lmb_bram_0/uart_platform_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_lmb_bram_0 || ORIG_REF_NAME==uart_platform_lmb_bram_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_xbar_0/uart_platform_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_xbar_0 || ORIG_REF_NAME==uart_platform_xbar_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_microblaze_0_axi_periph_0/uart_platform_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_microblaze_0_axi_periph_0 || ORIG_REF_NAME==uart_platform_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_microblaze_0_axi_intc_0/uart_platform_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_microblaze_0_axi_intc_0 || ORIG_REF_NAME==uart_platform_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_microblaze_0_xlconcat_0/uart_platform_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_microblaze_0_xlconcat_0 || ORIG_REF_NAME==uart_platform_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_mdm_1_0/uart_platform_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_mdm_1_0 || ORIG_REF_NAME==uart_platform_mdm_1_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_clk_wiz_1_0/uart_platform_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_clk_wiz_1_0 || ORIG_REF_NAME==uart_platform_clk_wiz_1_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_rst_clk_wiz_1_100M_0/uart_platform_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==uart_platform_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/uart_platform/ip/uart_platform_axi_uartlite_0_0/uart_platform_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_platform_axi_uartlite_0_0 || ORIG_REF_NAME==uart_platform_axi_uartlite_0_0} -quiet] -quiet

# XDC: c:/Xilinx/VivadoProjects/uart_platform/uart_platform.gen/sources_1/bd/uart_platform/uart_platform_ooc.xdc
