set_property SRC_FILE_INFO {cfile:C:/Xilinx/VivadoProjects/microblaze_mcu/microblaze_mcu.srcs/constrs_1/imports/VivadoProjects/Arty-A7-35-Master.xdc rfile:../../../microblaze_mcu.srcs/constrs_1/imports/VivadoProjects/Arty-A7-35-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { sys_clock }]; #IO_L12P_T1_MRCC_35 Sch=gclk[100]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D9    IOSTANDARD LVCMOS33 } [get_ports { reset }]; #IO_L6N_T0_VREF_16 Sch=btn[0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C9    IOSTANDARD LVCMOS33 } [get_ports { gpio_ip }]; #IO_L11P_T1_SRCC_16 Sch=btn[1]
